[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0

[program:postgres]
command=/usr/lib/postgresql/14/bin/postgres -D /var/lib/postgresql/14/main -c config_file=/etc/postgresql/14/main/postgresql.conf
user=postgres
autorestart=true

[program:rabbitmq]
command=/usr/sbin/rabbitmq-server
autorestart=true

[program:spring]
command=java -jar /app/apps/orchestrator/target/orchestrator-0.0.1-SNAPSHOT.jar
directory=/app/apps/orchestrator
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:worker]
command=python3 /app/apps/worker/main.py
directory=/app/apps/worker
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0