# GitHub Configuration
github.token=${GITHUB_TOKEN}

# RabbitMQ Configuration
spring.rabbitmq.addresses=${RABBITMQ_URL} 
# If we don't have a single URL, use these:
# spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
# spring.rabbitmq.username=${RABBIT_USER}
# spring.rabbitmq.password=${RABBIT_PWD}

# Database Configuration (Neon)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
server.port = 7860

# Security / Clerk
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${CLERK_JWKS_URI}